LIBC_OBJECTS =						\
		lib/libc/stdio/printf.o			\
		lib/libc/stdio/fprintf.o		\
		lib/libc/stdio/feof.o			\
		lib/libc/stdio/fopen.o			\
		lib/libc/stdio/fclose.o			\
		lib/libc/stdio/fread.o			\
		lib/libc/stdio/ferror.o			\
		lib/libc/stdio/fseek.o			\
		lib/libc/stdio/ftell.o			\
		lib/libc/stdio/fileno.o			\
		lib/libc/stdlib/atoi.o			\
		lib/libc/stdlib/bsearch.o		\
		lib/libc/stdlib/strtol.o		\
		lib/libc/stdlib/qsort.o			\
		lib/libc/string/bcmp.o			\
		lib/libc/string/ffs.o			\
		lib/libc/string/ffsl.o			\
		lib/libc/string/ffsll.o			\
		lib/libc/string/fls.o			\
		lib/libc/string/flsl.o			\
		lib/libc/string/flsll.o			\
		lib/libc/string/strcasecmp.o		\
		lib/libc/string/strcat.o		\
		lib/libc/string/strchr.o		\
		lib/libc/string/strcmp.o		\
		lib/libc/string/strcspn.o		\
		lib/libc/string/strcpy.o		\
		lib/libc/string/strlcat.o		\
		lib/libc/string/strlcpy.o		\
		lib/libc/string/strlen.o		\
		lib/libc/string/strncat.o		\
		lib/libc/string/strncmp.o		\
		lib/libc/string/strnlen.o		\
		lib/libc/string/strsep.o		\
		lib/libc/string/strstr.o		\
		lib/libc/string/memset.o		\
		lib/libc/string/memmove.o		\
		lib/libc/string/memchr.o		\
		lib/libc/string/memcmp.o		\
		lib/libc/string/bcopy.o			\
		lib/libc/string/bzero.o			\
		lib/libc/sys/fstat.o

LIBC_QUAD_OBJECTS =					\
		lib/libc/quad/qdivrem.o			\
		lib/libc/quad/udivdi3.o			\
		lib/libc/quad/umoddi3.o
