LIBFDT_OBJS =				\
	lib/libfdt/fdt_addresses.o	\
	lib/libfdt/fdt_empty_tree.o	\
	lib/libfdt/fdt_overlay.o	\
	lib/libfdt/fdt_ro.o		\
	lib/libfdt/fdt_rw.o		\
	lib/libfdt/fdt_strerror.o	\
	lib/libfdt/fdt_sw.o		\
	lib/libfdt/fdt_wip.o		\
	lib/libfdt/fdt.o

LIBFDT_INCS = lib/libfdt
