MBEDTLS_MDSHA_OBJS = 			\
	lib/mbedtls/library/md_wrap.o	\
	lib/mbedtls/library/md.o	\
	lib/mbedtls/library/md2.o	\
	lib/mbedtls/library/md4.o	\
	lib/mbedtls/library/md5.o	\
	lib/mbedtls/library/sha1.o	\
	lib/mbedtls/library/sha256.o	\
	lib/mbedtls/library/sha512.o	\
	lib/mbedtls/library/asn1parse.o	\
	lib/mbedtls/library/ripemd160.o

MBEDTLS_MDSHA_INCS = lib/mbedtls/include/
